#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'octokit'
require 'yaml'

# Read config
config = YAML.load_file('config.yml')
oauth_access_token = config.fetch('oauth_access_token')
repos = config.fetch('repos')

# TODO move to input arg
milestone_name = 'Cártama - dataservices'
end_date = '2016-06-16'


client = Octokit::Client.new(:access_token => oauth_access_token)

repos.each do |repo_name|

  # TODO deal with messages more nicely
  puts "Accessing repo " + repo_name
  repo = client.repository repo_name

  puts "    Checking if milestone " + milestone_name + " exists"
  rel = repo.rels[:milestones]
  milestones = rel.get.data
  matching_milestone = milestones.select { |m| m[:title] == milestone_name  }.first
  if matching_milestone
    puts "    The milestone " + milestone_name + " already exists"
    if matching_milestone.due_on == Time.parse(end_date)
      puts "        and the 'due by' field matches the expected one"
    else
      puts "        but the 'due by' field doesn't match"
      raise 'TODO not implemented yet'
    end
  else
    puts "    Creating milestone " + milestone_name
    client.create_milestone(repo_name, milestone_name, {due_on: Time.parse(end_date)})
  end

end
